# Agentic Commerce Narrator - Agent-OS Configuration
# Version: 3.0.0
# Last Updated: 2025-10-22

# Project Profile
version: "3.0.0"
project:
  name: "Agentic Commerce Narrator"
  type: "data-knowledge-graph"
  profile: "small"  # Focused data modeling project
  description: "Knowledge graph dataset for Traditional vs Agentic commerce transformation"

# Technology Stack
tech_stack:
  primary_focus: "Data Modeling & Content Creation"
  data_format: "JSON (143 files)"
  structure: "Knowledge Graph (1,426 nodes across 7 levels)"

  # Future tech stack (when visualization built)
  future:
    framework: "React 18"
    language: "TypeScript"
    styling: "Tailwind CSS v4"
    visualization: "ReactFlow, D3.js, Framer Motion"
    testing: "jest"
    build: "vite"

# Workflow Mode Configuration
workflow:
  # Two-mode system (simpler for data-focused work)
  default_mode: "fast"

  modes:
    # Fast Mode: 95% of data modeling work
    fast:
      description: "Quick data file updates, content enrichment, simple validations"
      token_budget: 1000
      time_estimate: "5-15 minutes"
      verification: "self-check"
      delegation: false
      documentation: "minimal"
      use_cases:
        - "Update JSON data files (capabilities, agents, personas)"
        - "Add benchmarks and projections to capabilities"
        - "Fix data validation errors"
        - "Update documentation"
        - "Content refinement and copy editing"
      validations:
        - "lint"
        - "type-check"
        - "data-validation"

    # Careful Mode: 5% of complex work
    careful:
      description: "Complex data model changes, graph structure modifications"
      token_budget: 5000
      time_estimate: "30-60 minutes"
      verification: "comprehensive"
      delegation: "conditional"
      documentation: "comprehensive"
      use_cases:
        - "Graph data model changes (7-level hierarchy)"
        - "Edge relationship modifications"
        - "Data schema updates"
        - "Large-scale data migrations"
        - "Performance-critical data structures"
      validations:
        - "lint"
        - "type-check"
        - "data-validation"
        - "schema-validation"
        - "graph-integrity-check"
      required_reviews:
        - "data-architect (for schema changes)"
        - "content-strategist (for large content updates)"

# Context Management (Data-Focused)
context:
  total_budget: 60000  # Smaller than web apps (30% of 200k window)

  tiers:
    # Tier 1: Data Schema & Structure (load once)
    core:
      budget: 20000
      load_frequency: "once"
      includes:
        - "README.md"
        - "data/manifest.json"
        - "data/types/**"
        - "data/utils/**"
        - ".agent-os/config.yml"

    # Tier 2: Domain Context (load per data area)
    domain:
      budget: 25000
      load_frequency: "per_data_area"
      examples:
        capabilities:
          - "data/capabilities/*.json"
          - "docs/data/capability-structure.md"
        agents:
          - "data/agents/*.json"
          - "docs/data/agent-types.md"
        graph:
          - "data/edges/*.json"
          - "docs/data/graph-structure.md"

    # Tier 3: Task-Specific (load per file)
    task:
      budget: 15000
      load_frequency: "per_file"
      includes:
        - "Specific JSON file being edited"
        - "Related validation rules"
        - "Similar data examples"

# Quality Gates
quality:
  # Pre-flight checks
  pre_flight:
    - "git status clean or approved"
    - "data validation passing (if exists)"
    - "✅ Mission alignment verified (.agent-os/instructions/compliance/mission-alignment.md)"
    - "✅ PRD scope verified (.agent-os/instructions/compliance/mission-alignment.md)"
    - "✅ Roadmap milestone verified (.agent-os/instructions/compliance/roadmap-compliance.md)"
    - "✅ Design system patterns identified (for UI work) (.agent-os/instructions/compliance/design-system.md)"

  # Post-flight checks
  post_flight:
    required:
      - "JSON syntax validation"
      - "data schema validation"
      - "graph integrity check"
      - "✅ Mission principle cited in commit message"
      - "✅ PRD user goal cited in commit (if applicable)"
      - "✅ Roadmap milestone/phase cited in commit"
      - "✅ Design system compliance verified (for UI work)"
    conditional:
      careful_mode:
        - "full graph compilation test"
        - "edge relationship validation"
        - "comprehensive compliance review"

  # Auto-rollback triggers
  rollback_on:
    - "JSON syntax errors"
    - "Schema validation failures"
    - "Graph integrity violations"
    - "Data corruption detected"
    - "Mission principle violations (see compliance/mission-alignment.md)"
    - "Out of scope features (see PRD Explicitly Rejected section)"
    - "Out of roadmap milestone (see compliance/roadmap-compliance.md)"
    - "Design system violations (for UI work) (see compliance/design-system.md)"

# Compliance Framework (MANDATORY)
compliance:
  enabled: true
  version: "1.0.0"

  # Mission & PRD alignment
  mission_alignment:
    enabled: true
    document: "docs/product/PRODUCT_MISSION.md"
    instructions: ".agent-os/instructions/compliance/mission-alignment.md"
    required_sections:
      - "Four Foundational Principles"
      - "Success Criteria"
      - "Explicitly Rejected Features"
    validation:
      - "Feature aligns with at least one foundational principle"
      - "Feature NOT in 'Explicitly Rejected' list"
      - "Implementation meets success criteria metrics"

  prd_alignment:
    enabled: true
    document: "docs/product/PRD.md"
    instructions: ".agent-os/instructions/compliance/mission-alignment.md"
    required_validation:
      - "Feature maps to primary user persona goal"
      - "Feature in 'In Scope (v1.0)' section"
      - "Feature NOT in 'Out of Scope' or 'Explicitly Rejected'"
      - "Supports 'Narrative Cockpit' vision (not 'Data Explorer')"

  design_system:
    enabled: true
    document: "docs/design/VISUAL_DESIGN_SYSTEM.md"
    instructions: ".agent-os/instructions/compliance/design-system.md"
    required_for:
      - "All UI components"
      - "All styling changes"
      - "New pages/routes"
      - "Component library additions"
    validation:
      - "Colors from defined Traditional/Agentic palette"
      - "Typography scale followed"
      - "Component patterns used (Cards, Buttons, etc.)"
      - "Icons from Lucide library (no emojis)"
      - "Accessibility: WCAG AAA (7:1 contrast)"
      - "Performance: animations < 200ms"

  roadmap_alignment:
    enabled: true
    document: "docs/product/IMPLEMENTATION_ROADMAP.md"
    instructions: ".agent-os/instructions/compliance/roadmap-compliance.md"
    enforce:
      - "Work only on current milestone tasks"
      - "Respect phase dependencies"
      - "Update milestone status on completion"
      - "No future milestone features implemented early"
    current_milestone:
      name: "Milestone 1: The Core Narrative (MVP)"
      status: "In Progress"
      phases:
        - "Phase 1.1: Data Architecture Foundation"
        - "Phase 1.2: Navigation Hierarchy"
        - "Phase 1.3: Application Shell"
        - "Phase 1.4: Comparison View"

  # Auto-rejection enforcement
  auto_reject:
    enabled: true
    triggers:
      mission_violations:
        - "Graph visualization as primary interface"
        - "Browse all capabilities view"
        - "Node-centric detail pages"
        - "Custom navigation modes (Browse, Visualize, Wizard)"
        - "Full graph exposure on load"

      design_violations:
        - "Random hex colors (not from design system)"
        - "Emojis in UI (enterprise aesthetic)"
        - "Custom font imports"
        - "Contrast ratios < 7:1"
        - "Inline styles (not using Tailwind)"

      scope_violations:
        - "Milestone 2+ features (Storyboard, Presentation mode)"
        - "Out of scope features (Graph viz, Multi-user, Export, etc.)"
        - "Future phase features implemented early"

# Traceability
traceability:
  # Audit logging
  audit_logs:
    enabled: true
    directory: ".agent-os/audit-logs"
    format: "YYYY-MM-DD-task-description.md"
    required_sections:
      - "Primary Request and Intent"
      - "Workflow Mode Selected"
      - "Data Files Modified"
      - "Validation Results"
      - "Token Usage"

  # Evidence-based status
  status_tracking:
    enabled: true
    format: "evidence-based"
    include:
      - "File paths modified"
      - "Validation passing status"
      - "Git commit hashes"
      - "Node counts and statistics"

  # Decision records
  decision_records:
    enabled: true
    directory: "docs/decisions"
    format: "ADR-NNN-[decision-name].md"
    trigger:
      - "Data model schema changes"
      - "Graph structure modifications"
      - "Content strategy decisions"

# Data-Specific Configuration
data_model:
  # Node hierarchy (7 levels)
  hierarchy:
    - "industry"
    - "domain"
    - "capability"
    - "function"
    - "persona"
    - "agent"
    - "concept"

  # Edge types
  edge_types:
    - "has_capability"
    - "performs_function"
    - "serves_persona"
    - "uses_agent"
    - "relates_to_concept"

  # Critical data integrity rules
  integrity_rules:
    - "All nodes must have unique IDs"
    - "All edges must reference existing nodes"
    - "Capability version must be 2.0.0"
    - "Benchmarks and projections must have sources"
    - "Domain-to-layer mappings must be preserved"

# Project-Specific Considerations
project_specific:
  # Current focus: Data modeling and enrichment
  current_phase: "data_enrichment"

  critical_files:
    - "data/manifest.json"
    - "data/capabilities/*.json (20 files)"
    - "data/functions/*.json (~100 files)"
    - "data/agents/*.json (~60 files)"
    - "data/edges/*.json"
    - "data/compiled-graph-data.ts"

  data_quality_standards:
    - "All capabilities at version 2.0.0"
    - "253 benchmarks with sources"
    - "475 projections with rationale"
    - "Consistent naming conventions"
    - "Complete metadata (description, tags, relationships)"

  content_standards:
    - "Professional, clear language"
    - "Quantifiable metrics where possible"
    - "Credible sources for benchmarks"
    - "Logical projections based on benchmarks"
    - "Industry-specific context preserved"

# Emergency Controls
emergency:
  halt_commands:
    - "/stop"
    - "/status"
    - "/continue"
    - "/rollback"

  auto_stop:
    - "JSON syntax errors (blocking)"
    - "Schema validation failures"
    - "Graph integrity violations"
    - "Large-scale data corruption detected"

# Performance Metrics
metrics:
  track:
    - "Token usage per task"
    - "Time per data file update"
    - "Validation pass/fail rates"
    - "Data quality improvements"

  targets:
    fast_mode_speed: "5-15 min per file"
    token_savings: "70-80% vs baseline"
    data_quality: "100% schema compliance"
    validation_pass_rate: ">95%"
